<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <PackageId>lscyane.BMS</PackageId>
    <Authors>茶音 麦粉 (@lscyane)</Authors>
    <Company>Tea Sound Project</Company>
    <CompanyShortName>TSP</CompanyShortName>
    <Copyright>(C) 2025-2026 茶音 麦粉 (@lscyane)</Copyright>
    <Description>Be-Music Source file Library for lscyane</Description>
    <RepositoryUrl>https://github.com/lscyane/lscyane.BMS</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression> 
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>0.0.2</VersionPrefix>
    <VersionSuffix></VersionSuffix>
    <BuildNumber>2</BuildNumber>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.8" />
  </ItemGroup>

</Project>
